/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/scene.ts"/>
/// <reference path="../config/game.ts"/>
/// <reference path="../config/screen.ts"/>
/// <reference path="../objects/asset.ts"/>
/// <reference path="../objects/button.ts"/>
/// <reference path="../objects/label.ts"/>
/// <reference path="../objects/scene.ts"/>
/// <reference path="../objects/ocean.ts"/>
/// <reference path="../scenes/exit.ts"/>
/// <reference path="../scenes/gameover.ts"/>
/// <reference path="../scenes/continue.ts"/>
/// <reference path="../scenes/shop.ts"/>
/// <reference path="../scenes/level.ts"/>
/// <reference path="../scenes/loading.ts"/>
/// <reference path="../scenes/instructions.ts"/>
/// <reference path="../scenes/menu.ts"/> 
//# sourceMappingURL=_reference.js.map